"""Accessibility evidence modeling and normalization modules."""

from accessroute.scoring.models import (
    BarrierType,
    EdgeAccessibilityEvidence,
    FindingType,
    InclineMeasurement,
    KerbType,
    NodeAccessibilityEvidence,
    SmoothnessType,
    SurfaceType,
    TactilePaving,
    WheelchairAccess,
    WidthMeasurement,
    SlopeDirection,
    NodeElevationEvidence,
    EdgeTerrainEvidence,
)
from accessroute.scoring.normalizer import (
    extract_edge_evidence,
    extract_node_evidence,
    normalize_barrier,
    normalize_incline,
    normalize_kerb,
    normalize_smoothness,
    normalize_surface,
    normalize_tactile_paving,
    normalize_wheelchair,
    normalize_width,
)

__all__ = [
    "BarrierType",
    "EdgeAccessibilityEvidence",
    "FindingType",
    "InclineMeasurement",
    "KerbType",
    "NodeAccessibilityEvidence",
    "SmoothnessType",
    "SurfaceType",
    "TactilePaving",
    "WheelchairAccess",
    "WidthMeasurement",
    "SlopeDirection",
    "NodeElevationEvidence",
    "EdgeTerrainEvidence",
    "extract_edge_evidence",
    "extract_node_evidence",
    "normalize_barrier",
    "normalize_incline",
    "normalize_kerb",
    "normalize_smoothness",
    "normalize_surface",
    "normalize_tactile_paving",
    "normalize_wheelchair",
    "normalize_width",
]

